# Generated by Django 5.2.7 on 2025-10-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof_user',
            name='user',
        ),
        migrations.AddField(
            model_name='prof_user',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prof_user',
            name='user_name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prof_user',
            name='img',
            field=models.FileField(default='assets/img/img_avatar.jpg', upload_to='profile_pics/'),
        ),
    ]
