# Generated by Django 5.2.7 on 2025-10-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_prof_user_user_prof_user_user_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prof_user',
            new_name='profile_user',
        ),
    ]
