# Generated by Django 5.2.7 on 2025-10-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_prof_user_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
