# Generated by Django 5.2.7 on 2025-10-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_pass',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
