# Generated by Django 5.2.7 on 2025-10-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_pass_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_pass',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
