# Generated by Django 5.2.7 on 2025-10-04 17:53

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_projects',
            name='created_date',
            field=django_jalali.db.models.jDateField(default=datetime.datetime.now),
        ),
    ]
