# Generated by Django 5.2.7 on 2025-10-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_create_projects_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_projects',
            name='langu',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
