# Generated by Django 5.2.7 on 2025-10-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_msgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgs',
            name='confirm_pro',
            field=models.IntegerField(),
        ),
    ]
