# Generated by Django 5.2.7 on 2025-10-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_msgs_confirm_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgs',
            name='is_read',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
