# Generated by Django 5.2.7 on 2025-10-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_msgs_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgs',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
