# Generated by Django 5.2.7 on 2025-10-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_msgs_receiver_alter_msgs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msgs',
            name='receiver',
        ),
    ]
