# Generated by Django 5.2.7 on 2025-10-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_msgs_receiver_alter_msgs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msgs',
            name='receiver',
        ),
    ]
