# Generated by Django 5.2.7 on 2025-10-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_msgs_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgs',
            name='confirm_msg',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
