# Generated by Django 5.2.7 on 2025-10-07 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_msgs_confirm_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgs',
            name='date_3',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
