# Generated by Django 5.2.7 on 2025-10-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_msgs_date_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='back_end',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('darsad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='basics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_1', models.CharField()),
                ('description_2', models.CharField()),
                ('description_3', models.CharField()),
                ('description_4', models.CharField()),
                ('image_main', models.ImageField(upload_to='img')),
                ('image_1', models.ImageField(upload_to='img')),
                ('image_2', models.ImageField(upload_to='img')),
                ('image_3', models.ImageField(upload_to='img')),
                ('image_4', models.ImageField(upload_to='img')),
                ('image_5', models.ImageField(upload_to='img')),
                ('image_6', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='front_end',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('darsad', models.IntegerField()),
            ],
        ),
    ]
