# Generated by Django 5.2.7 on 2025-10-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_back_end_basics_front_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='realtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('title_0', models.CharField()),
                ('title_1', models.CharField()),
                ('skills', models.CharField()),
                ('email', models.CharField()),
                ('instagram', models.CharField()),
                ('telegram', models.CharField()),
                ('image', models.ImageField(upload_to='img')),
                ('age', models.IntegerField()),
            ],
        ),
    ]
