# Generated by Django 5.2.7 on 2025-10-08 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_realtors'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_main', models.ImageField(upload_to='img')),
                ('image_1', models.ImageField(upload_to='img')),
                ('image_2', models.ImageField(upload_to='img')),
                ('image_3', models.ImageField(upload_to='img')),
                ('image_4', models.ImageField(upload_to='img')),
                ('image_5', models.ImageField(upload_to='img')),
                ('created_by', models.CharField()),
                ('title_main_1', models.CharField()),
                ('title_main_2', models.CharField()),
                ('title_1', models.CharField()),
                ('title_2', models.CharField()),
                ('title_3', models.CharField()),
                ('link_to', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='project_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('for_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project_sample')),
            ],
        ),
    ]
