# Generated by Django 5.2.7 on 2025-10-10 11:39

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_aboutus_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgs',
            name='reply_1',
            field=django_jalali.db.models.jDateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='msgs',
            name='reply_2',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='msgs',
            name='reply_msg',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
