# Generated by Django 5.2.7 on 2025-10-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_msgs_reply_1_msgs_reply_2_msgs_reply_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msgs',
            name='reply_1',
        ),
        migrations.RemoveField(
            model_name='msgs',
            name='reply_2',
        ),
        migrations.RemoveField(
            model_name='msgs',
            name='reply_msg',
        ),
    ]
