# Generated by Django 5.2.7 on 2025-10-16 09:56

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_msgs_reply_1_remove_msgs_reply_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgs',
            name='read_date1',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='msgs',
            name='read_date2',
            field=django_jalali.db.models.jDateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='msgs',
            name='reply',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
