# Generated by Django 5.2.7 on 2025-10-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_msgs_read_date1_msgs_read_date2_msgs_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_projects',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_projects',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
