# Generated by Django 5.2.7 on 2025-10-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_create_projects_day_create_projects_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_projects',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
