# Generated by Django 5.2.7 on 2025-10-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_create_projects_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_projects',
            name='price',
            field=models.CharField(),
        ),
    ]
