# Generated by Django 5.2.7 on 2025-10-17 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_create_projects_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_projects',
            name='date2',
            field=models.DateField(default=datetime.datetime(2025, 10, 17, 11, 0, 5, 544100)),
        ),
    ]
