# Generated by Django 5.2.7 on 2025-10-17 07:33

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_create_projects_date2'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_projects',
            name='created_date2',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='create_projects',
            name='date2',
            field=models.DateField(default=datetime.datetime(2025, 10, 17, 11, 3, 48, 154828)),
        ),
    ]
