# Generated by Django 5.2.7 on 2025-10-17 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_create_projects_created_date2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='title',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='create_projects',
            name='date2',
            field=models.DateField(default=datetime.datetime(2025, 10, 17, 11, 32, 16, 643387)),
        ),
    ]
