# Generated by Django 5.2.7 on 2025-10-17 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_title_contacts_contact_contacts_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.CharField()),
                ('contact', models.CharField()),
            ],
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='contact',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='name',
        ),
        migrations.AlterField(
            model_name='create_projects',
            name='date2',
            field=models.DateField(default=datetime.datetime(2025, 10, 17, 11, 43, 18, 450299)),
        ),
    ]
