# Generated by Django 5.2.7 on 2025-10-17 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_contact_rename_contact_contacts_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_s',
        ),
        migrations.AlterField(
            model_name='create_projects',
            name='date2',
            field=models.DateField(default=datetime.datetime(2025, 10, 17, 11, 47, 11, 749421)),
        ),
    ]
