# Generated by Django 5.2.7 on 2025-10-17 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_contact_contact_s_alter_create_projects_date2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_projects',
            name='date2',
            field=models.DateField(default=datetime.datetime(2025, 10, 17, 17, 46, 44, 880800)),
        ),
    ]
