# Generated by Django 5.2.7 on 2025-10-20 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_create_projects_date2'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.AlterField(
            model_name='create_projects',
            name='date2',
            field=models.DateField(default=datetime.datetime(2025, 10, 20, 18, 34, 19, 192964)),
        ),
    ]
